foreground #f1dfd8
background #1a120e

cursor #ffb694
cursor_text_color #542105

selection_foreground #542105
selection_background #ffb694

url_color #d1c88f

color0 #322824
color1 #ffb4ab
color2 #ffb694
color3 #d1c88f
color4 #713719
color5 #e6bead
color6 #4d471b
color7 #f1dfd8

color8 #52443d
color9 #ffb4ab
color10 #ffb694
color11 #d1c88f
color12 #713719
color13 #e6bead
color14 #4d471b
color15 #f1dfd8

active_tab_foreground #542105
active_tab_background #ffb694

inactive_tab_foreground #f1dfd8
inactive_tab_background #271e1a