rootcolor=131313ff

bordercolor=474747ff

focuscolor=005142ff

maximizescreencolor=b1ccc3ff

urgentcolor=ffb4abff

scratchpadcolor=a9cbe3ff

globalcolor=334c44ff

overlaycolor=294a5eff

jump_hit_fg_color=cde9dfff

jump_hit_bg_color=e2e2e2ff

jump_hit_border_color=5cdbbdff