rootcolor=131313ff

bordercolor=474747ff

focuscolor=004c6bff

maximizescreencolor=b6c9d8ff

urgentcolor=ffb4abff

scratchpadcolor=ccc1e9ff

globalcolor=374955ff

overlaycolor=4a4263ff

jump_hit_fg_color=d2e5f4ff

jump_hit_bg_color=e2e2e2ff

jump_hit_border_color=82cfffff