[config]
mode = "dark"
version_check = false
caching = false
show_color_picker = false

[templates.waybar]
input_path  = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/style.css"
post_hook   = "pkill waybar; sleep 0.3; waybar &>/dev/null &"

[templates.swaync]
input_path  = "~/.config/matugen/templates/swaync.css"
output_path = "~/.config/swaync/style.css"
post_hook   = "swaync-client --reload-css"

[templates.rofi]
input_path  = "~/.config/matugen/templates/colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.hyprland]
input_path  = "~/.config/matugen/templates/colors.lua"
output_path = "~/.config/hypr/modules/appearance/colors.lua"
post_hook   = "hyprctl reload"

[templates.cava]
input_path = '~/.config/matugen/templates/cava.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -USR2 -x cava || true'

[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.yazi]
input_path = '~/.config/matugen/templates/theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.swayosd]
input_path  = "~/.config/matugen/templates/swayosd.css"
output_path = "~/.config/swayosd/style.css"

# VS Code matugen extension
[templates.vscode-raw]
input_path = "./templates/vscode-colors"
output_path = "~/.cache/matugen/vscode-colors"

[templates.vscode-json]
input_path = "./templates/vscode-colors.json"
output_path = "~/.cache/matugen/vscode-colors.json"

[templates.librewolf]
input_path = "~/.config/matugen/templates/librewolf-colors.css"
output_path = "~/.config/librewolf/librewolf/tjk2f543.default/chrome/colors.css"
##Change tjk2f543 for name on your system in the same path

[templates.vesktop]
input_path = "~/.config/matugen/templates/vesktop.css"
output_path = "~/.config/vesktop/themes/vesktop.css"
