# ============================================================
# Foot — OozeSoft / Matugen
# ============================================================

[colors-dark]
background=131313
foreground=e2e2e2

cursor=471868 e2b6ff

selection-foreground=471868
selection-background=e2b6ff

## Normal/regular colors (palette 0-7)
regular0=0e0e0e
regular1=ffb4ab
regular2=e2b6ff
regular3=f4b7ba
regular4=5f3280
regular5=663b3e
regular6=d2c1d9
regular7=e2e2e2

## Bright colors (palette 8-15)
bright0=919191
bright1=ffb4ab
bright2=e2b6ff
bright3=f4b7ba
bright4=e2b6ff
bright5=f4b7ba
bright6=d2c1d9
bright7=e2e2e2