# ============================================================
# Foot — OozeSoft / Matugen
# ============================================================

[colors-dark]
background=131313
foreground=e2e2e2

cursor=00344b 82cfff

selection-foreground=00344b
selection-background=82cfff

## Normal/regular colors (palette 0-7)
regular0=0e0e0e
regular1=ffb4ab
regular2=82cfff
regular3=ccc1e9
regular4=004c6b
regular5=4a4263
regular6=b6c9d8
regular7=e2e2e2

## Bright colors (palette 8-15)
bright0=919191
bright1=ffb4ab
bright2=82cfff
bright3=ccc1e9
bright4=82cfff
bright5=ccc1e9
bright6=b6c9d8
bright7=e2e2e2