# ============================================================
# Foot — OozeSoft / Matugen
# ============================================================

[colors-dark]
background=131313
foreground=e2e2e2

cursor=5f1316 ffb3af

selection-foreground=5f1316
selection-background=ffb3af

## Normal/regular colors (palette 0-7)
regular0=0e0e0e
regular1=ffb4ab
regular2=ffb3af
regular3=e3c28c
regular4=7e2a2a
regular5=594319
regular6=e7bdba
regular7=e2e2e2

## Bright colors (palette 8-15)
bright0=919191
bright1=ffb4ab
bright2=ffb3af
bright3=e3c28c
bright4=ffb3af
bright5=e3c28c
bright6=e7bdba
bright7=e2e2e2