# ~/.config/hypr/hypridle.conf

general {
    lock_cmd = pidof hyprlock || hyprlock # Evita lanzar múltiples instancias
    before_sleep_cmd = loginctl lock-session # Bloquea antes de suspender el sistema
    after_sleep_cmd = hyprctl dispatch dpms on # Enciende monitores al despertar
}

# 1. Bajar brillo a los 2.5 minutos (150s) - Descomentar si usas brightnessctl
#listener {
#    timeout = 150
#    on-timeout = brightnessctl -s set 10%
#    on-resume = brightnessctl -r
#}

# 2. Bloquear la pantalla a los 20 minutos (1200s)
listener {
    timeout = 1200
    on-timeout = loginctl lock-session
}

# 3. Apagar monitores a los 25 minutos (1500s)
listener {
    timeout = 1500
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 4. Suspender el equipo a los 30 minutos (1800s)
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}