-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- HYPRLAND MAIN FILE                                    --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- hl.config({ autogenerated = true }) -- remove this line to remove the warning

-- ============================================================================
--  ENTRY POINT
-- ============================================================================
-- This file only requires() the modules below, in load order. Each module
-- keeps the original wiki links/comments from the autogenerated config, so
-- it stays self-documenting even if a section is empty or commented out.
--
-- require() paths are relative to this file (usually ~/.config/hypr/).
-- You can use "/" or "." as the path separator, e.g.:
--   require("modules/keybinds")  or  require("modules.keybinds")
-- See: https://wiki.hypr.land/Configuring/Start/
-- ============================================================================

require("modules.monitors")     -- MONITORS: outputs, mode, position, scale, mirroring
require("modules.programs")     -- MY PROGRAMS: terminal / file manager / launcher used elsewhere
require("modules.autostart")    -- AUTOSTART: daemons/apps launched on hyprland.start
require("modules.env")          -- ENVIRONMENT VARIABLES: cursor size, Nvidia vars, etc.
require("modules.permissions")  -- PERMISSIONS: hl.permission() ecosystem rules (needs restart)
require("modules.appearance")   -- LOOK AND FEEL: general (gaps/border/layout) + decoration (rounding/shadow/blur)
require("modules.animations")   -- ANIMATIONS: bezier curves, springs, per-element animation config
require("modules.layouts")      -- LAYOUTS: dwindle / master / scrolling options + workspace layout rules
require("modules.misc")         -- MISC: wallpaper / logo / other small toggles
require("modules.input")        -- INPUT: keyboard, mouse, touchpad, gestures, per-device overrides
require("modules.keybinds")     -- KEYBINDINGS: keyboard + mouse binds and dispatchers
require("modules.windowrules")  -- WINDOWS AND WORKSPACES: window rules + layer rules

