-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- HYPRLAND MAIN FILE                                    --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- ============================================================================
--  ENTRY POINT
-- ============================================================================
-- This file only requires() the modules below, in load order. Each module
-- keeps the original wiki links/comments from the autogenerated config, so
-- it stays self-documenting even if a section is empty or commented out.
-- See: https://wiki.hypr.land/Configuring/Start/
-- ============================================================================

-- ============================================================================
-- SYSTEM
-- ============================================================================
require("modules.system.env")
require("modules.system.permissions")
require("modules.system.misc")

-- ============================================================================
-- APPEARANCE
-- ============================================================================
require("modules.appearance.animations")
require("modules.appearance.appearance")
require("modules.appearance.colors")
require("modules.appearance.layouts")

-- ============================================================================
-- INPUT
-- ============================================================================
require("modules.input.input")
require("modules.input.keybinds")

-- ============================================================================
-- RULES
-- ============================================================================
require("modules.rules.windowrules")

-- ============================================================================
-- HARDWARE
-- ============================================================================
require("modules.hardware.monitors")

-- ============================================================================
-- STARTUP/PROGRAMS
-- ============================================================================
require("modules.startup.autostart")
require("modules.startup.programs")