# Plantilla corregida para Matugen (~/.config/matugen/templates/starship.toml)

format = """
[](fg:#ffb694)\
$username\
[](bg:#efbc95 fg:#ffb694)\
$hostname\
[](bg:#f1be7a fg:#efbc95)\
$directory\
[](fg:#f1be7a bg:#7b2f00)\
$git_branch\
$git_status\
[](fg:#7b2f00)\
$cmd_duration\
$line_break\
$character"""

add_newline = true

[username]
show_always = true
style_user = "bg:#ffb694 fg:#571f00 bold"
style_root = "bg:#ffb4ab fg:#690005 bold"
format = "[󱄅 $user]($style)"

[hostname]
ssh_only = false
style = "bg:#efbc95 fg:#48290c bold"
format = "[@$hostname]($style)"

[directory]
style = "bg:#f1be7a fg:#452b00 bold"
format = "[ 󰉋 $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = "󰊢 "
style = "bg:#7b2f00 fg:#ffdbcc bold"
format = "[ $symbol$branch]($style)"

[git_status]
style = "bg:#7b2f00 fg:#ffdbcc bold"
format = "[($all_status$ahead_behind)]($style) "
conflicted = "⚔ "
ahead = "⇡${count} "
behind = "⇣${count} "
untracked = "󰞋 "
modified = "󰏫 "
staged = "󰸞 "

[cmd_duration]
min_time = 2_000
style = "bold #f1be7a"
format = " 󱦟 [$duration]($style)"

[time]
disabled = false
style = "bold #ffb694"
format = "󰥔 [$time]($style)"
time_format = "%H:%M"

[character]
success_symbol = "[╭─ 󰅂](bold #ffb694) "
error_symbol = "[╭─ 󰅂](bold #ffb4ab) "