# Auto-generado por OozeShell (APPEARANCE). No editar a mano.
# Perfil: playful
animation_type_open=zoom
animation_type_close=zoom
layer_animation_type_open=zoom
layer_animation_type_close=zoom
fadein_begin_opacity=0.4
animation_duration_open=500
animation_duration_move=550
animation_duration_tag=400
animation_duration_close=400
animation_curve_open=0.34,1.56,0.64,1
animation_curve_move=0.34,1.4,0.64,1
animation_curve_tag=0.34,1.4,0.64,1
animation_curve_close=0.36,0,0.66,-0.2
