# Auto-generado por OozeShell (APPEARANCE). No editar a mano.
# Se regenera cada vez que cambias algo desde el panel de apariencia.
gappih=3
gappiv=3
gappoh=6
gappov=6
borderpx=3
border_radius=0
focused_opacity=1
unfocused_opacity=1
blur=1
blur_optimized=0
blur_params_radius=0
blur_params_num_passes=1
shadows=0
shadows_size=0
animations=1
