# Auto-generado por OozeShell (APPEARANCE). No editar a mano.
# Se regenera cada vez que cambias algo desde el panel de apariencia.
gappih=8
gappiv=8
gappoh=8
gappov=8
borderpx=0
border_radius=6
focused_opacity=1
unfocused_opacity=1
blur=0
blur_optimized=1
blur_params_radius=1
blur_params_num_passes=2
shadows=0
shadows_size=0
animations=1

