return {
    foreground = "#e2e2e2",
    background = "#131313",

    cursor_bg = "#82cfff",
    cursor_fg = "#00344b",

    selection_bg = "#82cfff",
    selection_fg = "#00344b",

    ansi = {
        "#0e0e0e",
        "#ffb4ab",
        "#82cfff",
        "#ccc1e9",
        "#004c6b",
        "#4a4263",
        "#b6c9d8",
        "#e2e2e2",
    },

    brights = {
        "#919191",
        "#ffb4ab",
        "#82cfff",
        "#ccc1e9",
        "#82cfff",
        "#ccc1e9",
        "#b6c9d8",
        "#e2e2e2",
    },
}