return {
    foreground = "#e2e2e2",
    background = "#131313",

    cursor_bg = "#5cdbbd",
    cursor_fg = "#00382d",

    selection_bg = "#5cdbbd",
    selection_fg = "#00382d",

    ansi = {
        "#0e0e0e",
        "#ffb4ab",
        "#5cdbbd",
        "#a9cbe3",
        "#005142",
        "#294a5e",
        "#b1ccc3",
        "#e2e2e2",
    },

    brights = {
        "#919191",
        "#ffb4ab",
        "#5cdbbd",
        "#a9cbe3",
        "#5cdbbd",
        "#a9cbe3",
        "#b1ccc3",
        "#e2e2e2",
    },
}